apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-09T16:41:23Z"
  generation: 1
  labels:
    app: try1
  name: try1
  namespace: default
  resourceVersion: "320359"
  uid: 5b40a8c4-8273-4a34-8f5c-fdc55ca0e3bf
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: try1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: try1
    spec:
      containers:
      - image: 10.111.231.7:5000/simpleapp
        imagePullPolicy: Always
        name: simpleapp
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
    - name: goproxy
      image: k8s.gcr.io/goproxy:0.1
      ports:
       - containerPort: 8080
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
         periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
status:
  availableReplicas: 6
  conditions:
  - lastTransitionTime: "2021-08-09T16:41:30Z"
    lastUpdateTime: "2021-08-09T16:41:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-09T16:41:23Z"
    lastUpdateTime: "2021-08-09T16:41:30Z"
    message: ReplicaSet "try1-764f4f79c5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 6
  replicas: 6
  updatedReplicas: 6
